TASK: "csnet-L-x2_train"

GPU: 0

MODEL:
  ARCH: "csnet"
  BASIC_SPLIT: [0.5,0.5]

AUTO:
  ENABLE: True
  PREDEFINE: ''
  FINETUNE: 300
  EXPAND: 2.0
  LOAD_WEIGHT: "FINETUNE"
  FLOPS:
    ENABLE: True
    WEIGHT: 3.0
    EXPAND: 1.0

FINETUNE:
  THRES: 1e-20

LOSS:
  MLOSS: 1

DATA:
  DIR: "datasets"
  PRETRAIN: ''
  BATCH_SIZE: 2
  WORKERS: 0
  IMAGE_H: 1024
  IMAGE_W: 1024
  RESUME: ""

VAL:
  DIR: "VAL"

TEST:
  DATASET_PATH: 'TEST/'
  DATASETS: ['']
  INTERVAL: 5
  ENABLE: False
  IMAGE_H: 1024
  IMAGE_W: 1024
  TESTALL: False
  CHECKPOINT:  "results/csnet-L-x2_train/checkpoint/checkpoint_epoch20.pth.tar"


SOLVER:
  METHOD: 'Adam_dynamic_weight_decay'
  LR: 1e-4
  ADJUST_STEP: True
  STEPS: [200,250]
  MAX_EPOCHS: 360
  FINETUNE:
    METHOD: 'Adam'
    LR: 1e-4
    ADJUST_STEP: True
    STEPS: [50,100]

PRUNE:
  BNS: True
  SHOW: True

